Bootstrap: docker-daemon
From: mercury/pridict:latest
%environment
    source /home/container_user/.bashrc
%runscript
   source /home/container_user/.bashrc
%startscript
    source /home/container_user/.bashrc